version: '3'

volumes:
  grafana:
    driver: local
  postgres:
    driver: local
  redis:
    driver: local
  minio:
    driver: local

networks:
  pastebinnet:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: loadbalancer
    volumes:
      - type: bind
        source: ./build/nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "8085:80"
    depends_on:
      - app
      - app2
    networks:
      - pastebinnet

  app2:
    image: pastebin
    container_name: app2
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      PG_DSN: ${PG_DSN}
      REDIS_DSN: ${REDIS_DSN}
      MINIO_DSN: ${MINIO_DSN}
      PORT: ${APP2_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ACTION_TIMEOUT: ${MINIO_ACTION_TIMEOUT}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
    ports:
      - ${APP2_PORT}
    networks:
      - pastebinnet
    depends_on:
      - postgres
      - redis

  app:
    image: pastebin
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      PG_DSN: ${PG_DSN}
      REDIS_DSN: ${REDIS_DSN}
      MINIO_DSN: ${MINIO_DSN}
      PORT: ${APP1_PORT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ACTION_TIMEOUT: ${MINIO_ACTION_TIMEOUT}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
    ports:
      - ${APP1_PORT}
    networks:
      - pastebinnet
    depends_on:
      - postgres
      - redis
      - minio

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: always
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - pastebinnet
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./build/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - pastebinnet
    depends_on:
      - app
      - app2

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - pastebinnet

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - redis:/data
    networks:
      - pastebinnet

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "8001:8001"
    command: server --console-address ":8001" /data
    volumes:
      - minio:/data
    networks:
      - pastebinnet
