// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/romankravchuk/pastebin/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// PastesRepo is an autogenerated mock type for the PastesRepo type
type PastesRepo struct {
	mock.Mock
}

// DeletePaste provides a mock function with given fields: _a0, _a1
func (_m *PastesRepo) DeletePaste(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaste provides a mock function with given fields: _a0, _a1
func (_m *PastesRepo) GetPaste(_a0 context.Context, _a1 string) (entity.Paste, error) {
	ret := _m.Called(_a0, _a1)

	var r0 entity.Paste
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (entity.Paste, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) entity.Paste); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(entity.Paste)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: _a0, _a1
func (_m *PastesRepo) Store(_a0 context.Context, _a1 entity.Paste) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.Paste) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePaste provides a mock function with given fields: _a0, _a1
func (_m *PastesRepo) UpdatePaste(_a0 context.Context, _a1 *entity.Paste) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Paste) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPastesRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewPastesRepo creates a new instance of PastesRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPastesRepo(t mockConstructorTestingTNewPastesRepo) *PastesRepo {
	mock := &PastesRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
