// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pastes": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pastes"
                ],
                "summary": "Создание нововой пасты",
                "parameters": [
                    {
                        "description": "Паста",
                        "name": "paste",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Paste"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "data": {
                                    "type": "object",
                                    "properties": {
                                        "paste": {
                                            "$ref": "#/definitions/github_com_romankravchuk_pastebin_internal_entity.PasteResponse"
                                        },
                                        "url": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/pastes/{hash}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pastes"
                ],
                "summary": "Получениие пасту по хешу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Хеш пасты",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pastes"
                ],
                "summary": "Удаление пасты по хешу",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Хеш пасты",
                        "name": "hash",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/token": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Получения авторизационных данных",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный код, сгенерированный OAuth2 приложением",
                        "name": "code",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Paste": {
            "description": "Тело запроса для создания пасты.",
            "type": "object",
            "required": [
                "format",
                "text"
            ],
            "properties": {
                "expires": {
                    "description": "Время, через которое паста становится не доступной",
                    "type": "string",
                    "enum": [
                        "30m",
                        "1h",
                        "1w",
                        "1mth"
                    ],
                    "example": "30m"
                },
                "format": {
                    "description": "Формат текста",
                    "type": "string",
                    "enum": [
                        "json",
                        "yaml",
                        "toml"
                    ],
                    "example": "json"
                },
                "name": {
                    "description": "Название",
                    "type": "string",
                    "maxLength": 255,
                    "example": "thie is paste"
                },
                "password": {
                    "description": "Пароль для получения доступа к пасте",
                    "type": "string",
                    "maxLength": 255,
                    "example": "hello"
                },
                "text": {
                    "description": "Текст пасты",
                    "type": "string",
                    "example": "this is my paste"
                }
            }
        },
        "github_com_romankravchuk_pastebin_internal_entity.PasteResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Pastebin API",
	Description:      "Implementation pastebin API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
